# Generated by Django 4.1.1 on 2022-10-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Income'},
        ),
    ]
